<?php
echo '<pre>';
echo '
&lt;?xml version="1.0"?&gt;
&lt;!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @category    Mage
 * @package     Mage_Customer
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
--&gt;
&lt;config&gt;
    &lt;modules&gt;
        &lt;Mage_Customer&gt;
            &lt;version&gt;1.6.2.0.1&lt;/version&gt;
        &lt;/Mage_Customer&gt;
    &lt;/modules&gt;
    &lt;admin&gt;
        &lt;fieldsets&gt;
            &lt;customer_dataflow&gt;
                &lt;store_id&gt;
                    &lt;system&gt;1&lt;/system&gt;
                &lt;/store_id&gt;
                &lt;store&gt;
                    &lt;ignore&gt;1&lt;/ignore&gt;
                &lt;/store&gt;
                &lt;entity_id&gt;
                    &lt;system&gt;1&lt;/system&gt;
                    &lt;ignore&gt;1&lt;/ignore&gt;
                &lt;/entity_id&gt;
                &lt;attribute_set_id&gt;
                    &lt;system&gt;1&lt;/system&gt;
                    &lt;ignore&gt;1&lt;/ignore&gt;
                &lt;/attribute_set_id&gt;
                &lt;attribute_set&gt;
                    &lt;ignore&gt;1&lt;/ignore&gt;
                &lt;/attribute_set&gt;
                &lt;entity_type_id&gt;
                    &lt;system&gt;1&lt;/system&gt;
                &lt;/entity_type_id&gt;
                &lt;increment_id&gt;
                    &lt;system&gt;1&lt;/system&gt;
                    &lt;ignore&gt;1&lt;/ignore&gt;
                &lt;/increment_id&gt;
                &lt;parent_id&gt;
                    &lt;system&gt;1&lt;/system&gt;
                &lt;/parent_id&gt;
                &lt;created_at&gt;
                    &lt;system&gt;1&lt;/system&gt;
                &lt;/created_at&gt;
                &lt;updated_at&gt;
                    &lt;system&gt;1&lt;/system&gt;
                &lt;/updated_at&gt;
                &lt;group_id&gt;
                    &lt;ignore&gt;1&lt;/ignore&gt;
                &lt;/group_id&gt;
                &lt;type_id&gt;
                    &lt;system&gt;1&lt;/system&gt;
                    &lt;ignore&gt;1&lt;/ignore&gt;
                &lt;/type_id&gt;
                &lt;type&gt;
                    &lt;ignore&gt;1&lt;/ignore&gt;
                &lt;/type&gt;
                &lt;created_in&gt;
                    &lt;system&gt;1&lt;/system&gt;
                    &lt;ignore&gt;1&lt;/ignore&gt;
                &lt;/created_in&gt;
                &lt;website_id&gt;
                    &lt;system&gt;1&lt;/system&gt;
                &lt;/website_id&gt;
                &lt;default_billing&gt;
                    &lt;system&gt;1&lt;/system&gt;
                &lt;/default_billing&gt;
                &lt;default_shipping&gt;
                    &lt;system&gt;1&lt;/system&gt;
                &lt;/default_shipping&gt;
                &lt;prefix&gt;
                    &lt;billing&gt;1&lt;/billing&gt;
                    &lt;shipping&gt;1&lt;/shipping&gt;
                    &lt;mapped&gt;1&lt;/mapped&gt;
                &lt;/prefix&gt;
                &lt;firstname&gt;
                    &lt;billing&gt;1&lt;/billing&gt;
                    &lt;shipping&gt;1&lt;/shipping&gt;
                    &lt;required&gt;1&lt;/required&gt;
                    &lt;mapped&gt;1&lt;/mapped&gt;
                &lt;/firstname&gt;
                &lt;middlename&gt;
                    &lt;billing&gt;1&lt;/billing&gt;
                    &lt;shipping&gt;1&lt;/shipping&gt;
                    &lt;mapped&gt;1&lt;/mapped&gt;
                &lt;/middlename&gt;
                &lt;lastname&gt;
                    &lt;billing&gt;1&lt;/billing&gt;
                    &lt;shipping&gt;1&lt;/shipping&gt;
                    &lt;required&gt;1&lt;/required&gt;
                    &lt;mapped&gt;1&lt;/mapped&gt;
                &lt;/lastname&gt;
                &lt;suffix&gt;
                    &lt;billing&gt;1&lt;/billing&gt;
                    &lt;shipping&gt;1&lt;/shipping&gt;
                    &lt;mapped&gt;1&lt;/mapped&gt;
                &lt;/suffix&gt;
                &lt;street_full&gt;
                    &lt;billing&gt;1&lt;/billing&gt;
                    &lt;shipping&gt;1&lt;/shipping&gt;
                &lt;/street_full&gt;
                &lt;street1&gt;
                    &lt;billing&gt;1&lt;/billing&gt;
                    &lt;shipping&gt;1&lt;/shipping&gt;
                    &lt;street&gt;1&lt;/street&gt;
                &lt;/street1&gt;
                &lt;street2&gt;
                    &lt;billing&gt;1&lt;/billing&gt;
                    &lt;shipping&gt;1&lt;/shipping&gt;
                    &lt;street&gt;1&lt;/street&gt;
                &lt;/street2&gt;
                &lt;street3&gt;
                    &lt;billing&gt;1&lt;/billing&gt;
                    &lt;shipping&gt;1&lt;/shipping&gt;
                    &lt;street&gt;1&lt;/street&gt;
                &lt;/street3&gt;
                &lt;street4&gt;
                    &lt;billing&gt;1&lt;/billing&gt;
                    &lt;shipping&gt;1&lt;/shipping&gt;
                    &lt;street&gt;1&lt;/street&gt;
                &lt;/street4&gt;
                &lt;street5&gt;
                    &lt;billing&gt;1&lt;/billing&gt;
                    &lt;shipping&gt;1&lt;/shipping&gt;
                    &lt;street&gt;1&lt;/street&gt;
                &lt;/street5&gt;
                &lt;street6&gt;
                    &lt;billing&gt;1&lt;/billing&gt;
                    &lt;shipping&gt;1&lt;/shipping&gt;
                    &lt;street&gt;1&lt;/street&gt;
                &lt;/street6&gt;
                &lt;street7&gt;
                    &lt;billing&gt;1&lt;/billing&gt;
                    &lt;shipping&gt;1&lt;/shipping&gt;
                    &lt;street&gt;1&lt;/street&gt;
                &lt;/street7&gt;
                &lt;street8&gt;
                    &lt;billing&gt;1&lt;/billing&gt;
                    &lt;shipping&gt;1&lt;/shipping&gt;
                    &lt;street&gt;1&lt;/street&gt;
                &lt;/street8&gt;
                &lt;city&gt;
                    &lt;billing&gt;1&lt;/billing&gt;
                    &lt;shipping&gt;1&lt;/shipping&gt;
                &lt;/city&gt;
                &lt;region&gt;
                    &lt;billing&gt;1&lt;/billing&gt;
                    &lt;shipping&gt;1&lt;/shipping&gt;
                &lt;/region&gt;
                &lt;country&gt;
                    &lt;billing&gt;1&lt;/billing&gt;
                    &lt;shipping&gt;1&lt;/shipping&gt;
                    &lt;billing_required&gt;1&lt;/billing_required&gt;
                    &lt;shipping_required&gt;1&lt;/shipping_required&gt;
                &lt;/country&gt;
                &lt;postcode&gt;
                    &lt;billing&gt;1&lt;/billing&gt;
                    &lt;shipping&gt;1&lt;/shipping&gt;
                    &lt;billing_required&gt;1&lt;/billing_required&gt;
                    &lt;shipping_required&gt;1&lt;/shipping_required&gt;
                &lt;/postcode&gt;
                &lt;telephone&gt;
                    &lt;billing&gt;1&lt;/billing&gt;
                    &lt;shipping&gt;1&lt;/shipping&gt;
                &lt;/telephone&gt;
                &lt;company&gt;
                    &lt;billing&gt;1&lt;/billing&gt;
                    &lt;shipping&gt;1&lt;/shipping&gt;
                &lt;/company&gt;
                &lt;fax&gt;
                    &lt;billing&gt;1&lt;/billing&gt;
                    &lt;shipping&gt;1&lt;/shipping&gt;
                &lt;/fax&gt;
            &lt;/customer_dataflow&gt;
        &lt;/fieldsets&gt;
    &lt;/admin&gt;
    &lt;global&gt;
        &lt;fieldsets&gt;
            &lt;customer_account&gt;
                &lt;prefix&gt;
                    &lt;create&gt;1&lt;/create&gt;
                    &lt;update&gt;1&lt;/update&gt;
                    &lt;name&gt;1&lt;/name&gt;
                &lt;/prefix&gt;
                &lt;firstname&gt;
                    &lt;create&gt;1&lt;/create&gt;
                    &lt;update&gt;1&lt;/update&gt;
                    &lt;name&gt;1&lt;/name&gt;
                &lt;/firstname&gt;
                &lt;middlename&gt;
                    &lt;create&gt;1&lt;/create&gt;
                    &lt;update&gt;1&lt;/update&gt;
                    &lt;name&gt;1&lt;/name&gt;
                &lt;/middlename&gt;
                &lt;lastname&gt;
                    &lt;create&gt;1&lt;/create&gt;
                    &lt;update&gt;1&lt;/update&gt;
                    &lt;name&gt;1&lt;/name&gt;
                &lt;/lastname&gt;
                &lt;suffix&gt;
                    &lt;create&gt;1&lt;/create&gt;
                    &lt;update&gt;1&lt;/update&gt;
                    &lt;name&gt;1&lt;/name&gt;
                &lt;/suffix&gt;
                &lt;email&gt;
                    &lt;create&gt;1&lt;/create&gt;
                    &lt;update&gt;1&lt;/update&gt;
                &lt;/email&gt;
                &lt;password&gt;
                    &lt;create&gt;1&lt;/create&gt;
                &lt;/password&gt;
                &lt;confirmation&gt;
                    &lt;create&gt;1&lt;/create&gt;
                &lt;/confirmation&gt;
                &lt;dob&gt;
                    &lt;create&gt;1&lt;/create&gt;
                    &lt;update&gt;1&lt;/update&gt;
                &lt;/dob&gt;
                &lt;taxvat&gt;
                    &lt;create&gt;1&lt;/create&gt;
                    &lt;update&gt;1&lt;/update&gt;
                &lt;/taxvat&gt;
                &lt;gender&gt;
                    &lt;create&gt;1&lt;/create&gt;
                    &lt;update&gt;1&lt;/update&gt;
                &lt;/gender&gt;
            &lt;/customer_account&gt;
            &lt;customer_address&gt;
                &lt;vat_id&gt;
                    &lt;to_quote_address&gt;*&lt;/to_quote_address&gt;
                &lt;/vat_id&gt;
                &lt;vat_is_valid&gt;
                    &lt;to_quote_address&gt;*&lt;/to_quote_address&gt;
                &lt;/vat_is_valid&gt;
                &lt;vat_request_id&gt;
                    &lt;to_quote_address&gt;*&lt;/to_quote_address&gt;
                &lt;/vat_request_id&gt;
                &lt;vat_request_date&gt;
                    &lt;to_quote_address&gt;*&lt;/to_quote_address&gt;
                &lt;/vat_request_date&gt;
                &lt;vat_request_success&gt;
                    &lt;to_quote_address&gt;*&lt;/to_quote_address&gt;
                &lt;/vat_request_success&gt;
            &lt;/customer_address&gt;
            &lt;sales_convert_order_address&gt;
                &lt;vat_id&gt;
                    &lt;to_quote_address&gt;*&lt;/to_quote_address&gt;
                &lt;/vat_id&gt;
                &lt;vat_is_valid&gt;
                    &lt;to_quote_address&gt;*&lt;/to_quote_address&gt;
                &lt;/vat_is_valid&gt;
                &lt;vat_request_id&gt;
                    &lt;to_quote_address&gt;*&lt;/to_quote_address&gt;
                &lt;/vat_request_id&gt;
                &lt;vat_request_date&gt;
                    &lt;to_quote_address&gt;*&lt;/to_quote_address&gt;
                &lt;/vat_request_date&gt;
                &lt;vat_request_success&gt;
                    &lt;to_quote_address&gt;*&lt;/to_quote_address&gt;
                &lt;/vat_request_success&gt;
            &lt;/sales_convert_order_address&gt;
            &lt;sales_convert_quote_address&gt;
                &lt;vat_id&gt;
                    &lt;to_order_address&gt;*&lt;/to_order_address&gt;
                    &lt;to_customer_address&gt;*&lt;/to_customer_address&gt;
                &lt;/vat_id&gt;
                &lt;vat_is_valid&gt;
                    &lt;to_order_address&gt;*&lt;/to_order_address&gt;
                    &lt;to_customer_address&gt;*&lt;/to_customer_address&gt;
                &lt;/vat_is_valid&gt;
                &lt;vat_request_id&gt;
                    &lt;to_order_address&gt;*&lt;/to_order_address&gt;
                    &lt;to_customer_address&gt;*&lt;/to_customer_address&gt;
                &lt;/vat_request_id&gt;
                &lt;vat_request_date&gt;
                    &lt;to_order_address&gt;*&lt;/to_order_address&gt;
                    &lt;to_customer_address&gt;*&lt;/to_customer_address&gt;
                &lt;/vat_request_date&gt;
                &lt;vat_request_success&gt;
                    &lt;to_order_address&gt;*&lt;/to_order_address&gt;
                    &lt;to_customer_address&gt;*&lt;/to_customer_address&gt;
                &lt;/vat_request_success&gt;
            &lt;/sales_convert_quote_address&gt;
            &lt;sales_copy_order_billing_address&gt;
                &lt;vat_id&gt;
                    &lt;to_order&gt;*&lt;/to_order&gt;
                &lt;/vat_id&gt;
                &lt;vat_is_valid&gt;
                    &lt;to_order&gt;*&lt;/to_order&gt;
                &lt;/vat_is_valid&gt;
                &lt;vat_request_id&gt;
                    &lt;to_order&gt;*&lt;/to_order&gt;
                &lt;/vat_request_id&gt;
                &lt;vat_request_date&gt;
                    &lt;to_order&gt;*&lt;/to_order&gt;
                &lt;/vat_request_date&gt;
                &lt;vat_request_success&gt;
                    &lt;to_order&gt;*&lt;/to_order&gt;
                &lt;/vat_request_success&gt;
            &lt;/sales_copy_order_billing_address&gt;
        &lt;/fieldsets&gt;
        &lt;customer&gt;
            &lt;address&gt;
                &lt;formats&gt;
                    &lt;text translate="title" module="customer"&gt;
                        &lt;title&gt;Text&lt;/title&gt;
                    &lt;/text&gt;
                    &lt;oneline translate="title" module="customer"&gt;
                        &lt;title&gt;Text One Line&lt;/title&gt;
                    &lt;/oneline&gt;
                    &lt;html translate="title" module="customer"&gt;
                        &lt;title&gt;HTML&lt;/title&gt;
                        &lt;htmlEscape&gt;true&lt;/htmlEscape&gt;
                    &lt;/html&gt;
                    &lt;pdf translate="title" module="customer"&gt;
                        &lt;title&gt;PDF&lt;/title&gt;
                    &lt;/pdf&gt;
                    &lt;js_template template="title" module="customer"&gt;
                        &lt;title&gt;JavaScript Template&lt;/title&gt;
                    &lt;/js_template&gt;
                &lt;/formats&gt;
            &lt;/address&gt;
        &lt;/customer&gt;
        &lt;blocks&gt;
            &lt;customer&gt;
                &lt;class&gt;Mage_Customer_Block&lt;/class&gt;
            &lt;/customer&gt;
        &lt;/blocks&gt;
        &lt;models&gt;
            &lt;customer&gt;
                &lt;class&gt;Mage_Customer_Model&lt;/class&gt;
                &lt;resourceModel&gt;customer_resource&lt;/resourceModel&gt;
            &lt;/customer&gt;
            &lt;customer_resource&gt;
                &lt;class&gt;Mage_Customer_Model_Resource&lt;/class&gt;
                &lt;deprecatedNode&gt;customer_mysql4&lt;/deprecatedNode&gt;
                &lt;entities&gt;
                    &lt;entity&gt;
                        &lt;table&gt;customer_entity&lt;/table&gt;
                    &lt;/entity&gt;
                    &lt;address_entity&gt;
                        &lt;table&gt;customer_address_entity&lt;/table&gt;
                    &lt;/address_entity&gt;
                    &lt;value_prefix&gt;
                        &lt;table&gt;customer_entity&lt;/table&gt;
                    &lt;/value_prefix&gt;
                    &lt;customer_group&gt;
                        &lt;table&gt;customer_group&lt;/table&gt;
                    &lt;/customer_group&gt;
                    &lt;eav_attribute&gt;
                        &lt;table&gt;customer_eav_attribute&lt;/table&gt;
                    &lt;/eav_attribute&gt;
                    &lt;eav_attribute_website&gt;
                        &lt;table&gt;customer_eav_attribute_website&lt;/table&gt;
                    &lt;/eav_attribute_website&gt;
                    &lt;form_attribute&gt;
                        &lt;table&gt;customer_form_attribute&lt;/table&gt;
                    &lt;/form_attribute&gt;
                &lt;/entities&gt;
            &lt;/customer_resource&gt;
        &lt;/models&gt;
        &lt;resources&gt;
            &lt;customer_setup&gt;
                &lt;setup&gt;
                    &lt;module&gt;Mage_Customer&lt;/module&gt;
                    &lt;class&gt;Mage_Customer_Model_Resource_Setup&lt;/class&gt;
                &lt;/setup&gt;
            &lt;/customer_setup&gt;
        &lt;/resources&gt;
        &lt;template&gt;
            &lt;email&gt;
                &lt;customer_create_account_email_template translate="label" module="customer"&gt;
                    &lt;label&gt;New account&lt;/label&gt;
                    &lt;file&gt;account_new.html&lt;/file&gt;
                    &lt;type&gt;html&lt;/type&gt;
                &lt;/customer_create_account_email_template&gt;
                &lt;customer_create_account_email_confirmation_template translate="label" module="customer"&gt;
                    &lt;label&gt;New account confirmation key&lt;/label&gt;
                    &lt;file&gt;account_new_confirmation.html&lt;/file&gt;
                    &lt;type&gt;html&lt;/type&gt;
                &lt;/customer_create_account_email_confirmation_template&gt;
                &lt;customer_create_account_email_confirmed_template translate="label" module="customer"&gt;
                    &lt;label&gt;New account confirmed&lt;/label&gt;
                    &lt;file&gt;account_new_confirmed.html&lt;/file&gt;
                    &lt;type&gt;html&lt;/type&gt;
                &lt;/customer_create_account_email_confirmed_template&gt;
                &lt;customer_password_forgot_email_template translate="label" module="customer"&gt;
                    &lt;label&gt;Forgot Password&lt;/label&gt;
                    &lt;file&gt;account_password_reset_confirmation.html&lt;/file&gt;
                    &lt;type&gt;html&lt;/type&gt;
                &lt;/customer_password_forgot_email_template&gt;
                &lt;customer_password_remind_email_template translate="label" module="customer"&gt;
                    &lt;label&gt;Remind Password&lt;/label&gt;
                    &lt;file&gt;password_new.html&lt;/file&gt;
                    &lt;type&gt;html&lt;/type&gt;
                &lt;/customer_password_remind_email_template&gt;
            &lt;/email&gt;
        &lt;/template&gt;
        &lt;events&gt;
            &lt;customer_address_save_before&gt;
                &lt;observers&gt;
                    &lt;customer_address_before_save_viv_observer&gt;
                        &lt;class&gt;customer/observer&lt;/class&gt;
                        &lt;method&gt;beforeAddressSave&lt;/method&gt;
                    &lt;/customer_address_before_save_viv_observer&gt;
                &lt;/observers&gt;
            &lt;/customer_address_save_before&gt;
            &lt;customer_address_save_after&gt;
                &lt;observers&gt;
                    &lt;customer_addres_after_save_viv_observer&gt;
                        &lt;class&gt;customer/observer&lt;/class&gt;
                        &lt;method&gt;afterAddressSave&lt;/method&gt;
                    &lt;/customer_addres_after_save_viv_observer&gt;
                &lt;/observers&gt;
            &lt;/customer_address_save_after&gt;
        &lt;/events&gt;
    &lt;/global&gt;
    &lt;adminhtml&gt;
        &lt;translate&gt;
            &lt;modules&gt;
                &lt;Mage_Customer&gt;
                    &lt;files&gt;
                        &lt;default&gt;Mage_Customer.csv&lt;/default&gt;
                    &lt;/files&gt;
                &lt;/Mage_Customer&gt;
            &lt;/modules&gt;
        &lt;/translate&gt;
    &lt;/adminhtml&gt;
    &lt;frontend&gt;
        &lt;secure_url&gt;
            &lt;customer&gt;/customer/&lt;/customer&gt;
        &lt;/secure_url&gt;
        &lt;events&gt;
            &lt;controller_action_layout_load_before&gt;
                &lt;observers&gt;
                    &lt;customer_is_logged_in_observer&gt;
                        &lt;class&gt;customer/observer&lt;/class&gt;
                        &lt;method&gt;beforeLoadLayout&lt;/method&gt;
                    &lt;/customer_is_logged_in_observer&gt;
                &lt;/observers&gt;
            &lt;/controller_action_layout_load_before&gt;
            &lt;sales_model_service_quote_submit_after&gt;
                &lt;observers&gt;
                    &lt;restore_customer_group_id&gt;
                        &lt;class&gt;customer/observer&lt;/class&gt;
                        &lt;method&gt;quoteSubmitAfter&lt;/method&gt;
                    &lt;/restore_customer_group_id&gt;
                &lt;/observers&gt;
            &lt;/sales_model_service_quote_submit_after&gt;
        &lt;/events&gt;
        &lt;routers&gt;
            &lt;customer&gt;
                &lt;use&gt;standard&lt;/use&gt;
                &lt;args&gt;
                    &lt;module&gt;Mage_Customer&lt;/module&gt;
                    &lt;frontName&gt;customer&lt;/frontName&gt;
                &lt;/args&gt;
            &lt;/customer&gt;
        &lt;/routers&gt;
        &lt;translate&gt;
            &lt;modules&gt;
                &lt;Mage_Customer&gt;
                    &lt;files&gt;
                        &lt;default&gt;Mage_Customer.csv&lt;/default&gt;
                    &lt;/files&gt;
                &lt;/Mage_Customer&gt;
            &lt;/modules&gt;
        &lt;/translate&gt;
        &lt;layout&gt;
            &lt;updates&gt;
                &lt;customer module="Mage_Customer"&gt;
                    &lt;file&gt;customer.xml&lt;/file&gt;
                &lt;/customer&gt;
            &lt;/updates&gt;
        &lt;/layout&gt;
    &lt;/frontend&gt;
    &lt;default&gt;
        &lt;customer&gt;
            &lt;account_share&gt;
                &lt;scope&gt;1&lt;/scope&gt;
            &lt;/account_share&gt;
            &lt;create_account&gt;
                &lt;confirm&gt;0&lt;/confirm&gt;
                &lt;default_group&gt;1&lt;/default_group&gt;
                &lt;tax_calculation_address_type&gt;billing&lt;/tax_calculation_address_type&gt;
                &lt;email_domain&gt;example.com&lt;/email_domain&gt;
                &lt;email_identity&gt;general&lt;/email_identity&gt;
                &lt;email_template&gt;customer_create_account_email_template&lt;/email_template&gt;
                &lt;email_confirmation_template&gt;customer_create_account_email_confirmation_template&lt;/email_confirmation_template&gt;
                &lt;email_confirmed_template&gt;customer_create_account_email_confirmed_template&lt;/email_confirmed_template&gt;
                &lt;vat_frontend_visibility&gt;0&lt;/vat_frontend_visibility&gt;
            &lt;/create_account&gt;
            &lt;default&gt;
                &lt;group&gt;1&lt;/group&gt;
            &lt;/default&gt;
            &lt;password&gt;
                &lt;forgot_email_identity&gt;support&lt;/forgot_email_identity&gt;
                &lt;forgot_email_template&gt;customer_password_forgot_email_template&lt;/forgot_email_template&gt;
                &lt;remind_email_template&gt;customer_password_remind_email_template&lt;/remind_email_template&gt;
                &lt;reset_link_expiration_period&gt;1&lt;/reset_link_expiration_period&gt;
            &lt;/password&gt;
            &lt;address&gt;
                &lt;street_lines&gt;2&lt;/street_lines&gt;
                &lt;prefix_show/&gt;
                &lt;prefix_options/&gt;
                &lt;middlename_show/&gt;
                &lt;suffix_show/&gt;
                &lt;suffix_options/&gt;
                &lt;dob_show/&gt;
                &lt;gender_show/&gt;
            &lt;/address&gt;
            &lt;startup&gt;
                &lt;redirect_dashboard&gt;1&lt;/redirect_dashboard&gt;
            &lt;/startup&gt;
            &lt;address_templates&gt;
                &lt;text&gt;{{depend prefix}}{{var prefix}} {{/depend}}{{var firstname}} {{depend middlename}}{{var middlename}} {{/depend}}{{var lastname}}{{depend suffix}} {{var suffix}}{{/depend}}
{{depend company}}{{var company}}{{/depend}}
{{if street1}}{{var street1}}
{{/if}}
{{depend street2}}{{var street2}}{{/depend}}
{{depend street3}}{{var street3}}{{/depend}}
{{depend street4}}{{var street4}}{{/depend}}
{{if city}}{{var city}},  {{/if}}{{if region}}{{var region}}, {{/if}}{{if postcode}}{{var postcode}}{{/if}}
{{var country}}
T: {{var telephone}}
{{depend fax}}F: {{var fax}}{{/depend}}
{{depend vat_id}}VAT: {{var vat_id}}{{/depend}}&lt;/text&gt;
                &lt;oneline&gt;{{depend prefix}}{{var prefix}} {{/depend}}{{var firstname}} {{depend middlename}}{{var middlename}} {{/depend}}{{var lastname}}{{depend suffix}} {{var suffix}}{{/depend}}, {{var street}}, {{var city}}, {{var region}} {{var postcode}}, {{var country}}&lt;/oneline&gt;
                &lt;html&gt;{{depend prefix}}{{var prefix}} {{/depend}}{{var firstname}} {{depend middlename}}{{var middlename}} {{/depend}}{{var lastname}}{{depend suffix}} {{var suffix}}{{/depend}}br/&gt;
{{depend company}}{{var company}}br /&gt;{{/depend}}
{{if street1}}{{var street1}}br /&gt;{{/if}}
{{depend street2}}{{var street2}}br /&gt;{{/depend}}
{{depend street3}}{{var street3}}br /&gt;{{/depend}}
{{depend street4}}{{var street4}}br /&gt;{{/depend}}
{{if city}}{{var city}},  {{/if}}{{if region}}{{var region}}, {{/if}}{{if postcode}}{{var postcode}}{{/if}}br/&gt;
{{var country}}br/&gt;
{{depend telephone}}T: {{var telephone}}{{/depend}}
{{depend fax}}br/&gt;F: {{var fax}}{{/depend}}
{{depend vat_id}}br/&gt;VAT: {{var vat_id}}{{/depend}}&lt;/html&gt;
                &lt;pdf&gt;{{depend prefix}}{{var prefix}} {{/depend}}{{var firstname}} {{depend middlename}}{{var middlename}} {{/depend}}{{var lastname}}{{depend suffix}} {{var suffix}}{{/depend}}|
{{depend company}}{{var company}}|{{/depend}}
{{if street1}}{{var street1}}
{{/if}}
{{depend street2}}{{var street2}}|{{/depend}}
{{depend street3}}{{var street3}}|{{/depend}}
{{depend street4}}{{var street4}}|{{/depend}}
{{if city}}{{var city}},|{{/if}}
{{if region}}{{var region}}, {{/if}}{{if postcode}}{{var postcode}}{{/if}}|
{{var country}}|
{{depend telephone}}T: {{var telephone}}{{/depend}}|
{{depend fax}}br/&gt;F: {{var fax}}{{/depend}}|
{{depend vat_id}}br/&gt;VAT: {{var vat_id}}{{/depend}}|&lt;/pdf&gt;
                &lt;js_template&gt;#{prefix} #{firstname} #{middlename} #{lastname} #{suffix}br/&gt;#{company}br/&gt;#{street0}br/&gt;#{street1}br/&gt;#{street2}br/&gt;#{street3}br/&gt;#{city}, #{region}, #{postcode}br/&gt;#{country_id}br/&gt;T: #{telephone}br/&gt;F: #{fax}br/&gt;VAT: #{vat_id}&lt;/js_template&gt;
            &lt;/address_templates&gt;
        &lt;/customer&gt;
    &lt;/default&gt;
&lt;/config&gt;';
echo '</pre>';